const data = {
  categories: [
    {
      name: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686416958/MY%20ECOMMERCE/design-drag-race-shoes-with-gravis-racing-vector-motif_712527-1391_zndpkg.jpg",
    },
    {
      name: "Heels",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686417272/MY%20ECOMMERCE/product5_850x_v1anp1.jpg",
    },
    {
      name: "Sandals",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686417599/MY%20ECOMMERCE/300933009FUCHSIA_2_1024x1024_bpowc2.jpg",
    },
  ],

  products: [
    {
      title: "Knotted Thong Sandals",
      oldPrice: 350,
      newPrice: 300,
      desc: "Flat Sandal Women Summer Zipper Canvas Sandals Female Light Weight Casual Shoes For Women Fashion Our Perth sliders are a holiday essential. With a woven textured upper and metallic thread detailing, they’ll see you from the daytime to evening.",
      color: "Gold",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686408086/MY%20ECOMMERCE/3.1_korziu.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: true,
      brand: "Gionee",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Nautical Stripe EVA Flip Flops",
      oldPrice: 150,
      newPrice: 150,
      desc: "With their spongy EVA soles, smart monogram print and nautical navy hue, these flip-flops make the perfect poolside companions.",
      color: "Navy",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686407808/MY%20ECOMMERCE/14.1_rui9hn.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: true,
      brand: "Athlego",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Bethany Beaded Rose Gold Sandals",
      oldPrice: 190,
      newPrice: 190,
      desc: "Heavily beaded for endless shine, our Bethany rose-gold sandals finish holiday outfits with pure glamour. This T-bar shape features a toe post and buckle fastenings",
      color: "GoldenRod",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686407749/MY%20ECOMMERCE/1.1_rqsz6t.jpg",
      category: "Sandals",
      isFeatured: true,
      trending: false,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Perth Fabric Twist Sliders",
      oldPrice: 150,
      newPrice: 125,
      desc: "Flat Sandal Women Summer Zipper Canvas Sandals Female Light Weight Casual Shoes For Women Fashion Our Perth sliders are a holiday essential. With a woven textured upper and metallic thread detailing, they’ll see you from the daytime to evening.",
      color: "Gold",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686407727/MY%20ECOMMERCE/15.1_mccnwd.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: true,
      brand: "Fila",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Palm Print EVA Flip Flops",
      oldPrice: 150,
      newPrice: 150,
      desc: "Go totally tropical on holiday with these flip flops. This pair features patent thong straps and EVA soles, with a colourful print of painterly palms on the footbed.",
      color: "Pink",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686407710/MY%20ECOMMERCE/4.1_vs2uzt.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: true,
      brand: "Gionee",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Wide Strap Mule Sandals",
      oldPrice: 180,
      newPrice: 180,
      desc: "Flat Sandal Women Summer Zipper Canvas Sandals Female Light Weight Casual Shoes For Women Fashion Our Perth sliders are a holiday essential. With a woven textured upper and metallic thread detailing, they’ll see you from the daytime to evening.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686407682/MY%20ECOMMERCE/7.1_yb7ccw.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: true,
      brand: "Metro",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Amani Mule Shoes",
      oldPrice: 210,
      newPrice: 210,
      desc: "Elevate any smart look with our Amani mule shoes, featuring an on-trend tortoiseshell detail and leather construction for a luxe finish. These backless flats are a must have warm weather style.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686411224/MY%20ECOMMERCE/11.1_fe0vyk.jpg",
      category: "Sandals",
      isFeatured: true,
      trending: false,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Diamante Buckle Sliders",
      oldPrice: 190,
      newPrice: 190,
      desc: "Add a touch of glam to any sunny-day ensemble with these sparkly sliders. The buckled straps are drenched in teeny diamantes and the footbeds are moulded for comfort.",
      color: "Silver",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686411341/MY%20ECOMMERCE/13.1_llzwdd.jpg",
      category: "Sandals",
      isFeatured: true,
      trending: false,
      brand: "Antartic",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Woven Sliders",
      oldPrice: 198,
      newPrice: 190,
      desc: "Our sliders will go great with your holiday. They’re crafted from a faux leather material with a woven finish, meaning they’ll suit both day and evening looks. They have a slight heel and padded footbed for comfort all day long; the ultimate finishing touch.",
      color: "White",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686411550/MY%20ECOMMERCE/8.1_vvueyl.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: true,
      brand: "Athlego",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Diamante Espadrilles",
      oldPrice: 140,
      newPrice: 115,
      desc: "Add a touch of glam to any sunny-day ensemble with these sparkly espadrilles. They’re made from soft suedette with a gem-embellished front and classic woven sole.",
      color: "Pink",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686411831/MY%20ECOMMERCE/12.1_udxvia.jpg",
      category: "Sandals",
      isFeatured: true,
      trending: false,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "EVA Polka Dot Print Flip Flops",
      oldPrice: 100,
      newPrice: 100,
      desc: "With their spongy EVA soles, fun polka dot print and monochrome hue, these flip-flops make the perfect poolside companions.",
      color: "White",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686417660/MY%20ECOMMERCE/2.1_l0q2ql.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: false,
      brand: "Mochi",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Tortoiseshell Eva Thong Flip Flops",
      oldPrice: 110,
      newPrice: 110,
      desc: "Add a touch of the tortoiseshell trend to your holiday edit with our flip flops. This pair features patent thong straps and EVA soles.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686417802/MY%20ECOMMERCE/16.1_xpo2vu.jpg",
      category: "Sandals",
      isFeatured: false,
      trending: false,
      brand: "Athlego",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Black High Heels",
      oldPrice: 420,
      newPrice: 420,
      desc: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686413434/MY%20ECOMMERCE/product4_850x_jxniiz.jpg",
      category: "Heels",
      isFeatured: true,
      trending: false,
      brand: "Campus",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Stylish Slip Ons",
      oldPrice: 550,
      newPrice: 529,
      desc: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos.",
      color: "Brown",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686413703/MY%20ECOMMERCE/product8_850x_srnpte.jpg",
      category: "Heels",
      isFeatured: true,
      trending: false,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Stiletto Heels Formal",
      oldPrice: 190,
      newPrice: 190,
      desc: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo",
      color: "Red",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686413903/MY%20ECOMMERCE/product12_850x_gn9vpb.jpg",
      category: "Heels",
      isFeatured: true,
      trending: false,
      brand: "Aldo",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Black Slip ons",
      oldPrice: 360,
      newPrice: 360,
      desc: "Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686414018/MY%20ECOMMERCE/product30_850x_wiitre.jpg",
      category: "Heels",
      isFeatured: true,
      trending: false,
      brand: "Mochi",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Stiletto Sandals",
      oldPrice: 850,
      newPrice: 789,
      desc: "Omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686414275/MY%20ECOMMERCE/product21_850x_v9pd89.jpg",
      category: "Heels",
      isFeatured: false,
      trending: true,
      brand: "Mochi",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Heels Formals",
      oldPrice: 1000,
      newPrice: 700,
      desc: "Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volup",
      color: "Sandal",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686414637/MY%20ECOMMERCE/product26_850x_pljmlu.jpg",
      category: "Heels",
      isFeatured: false,
      trending: true,
      brand: "Aldo",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Slip On Moccasins",
      oldPrice: 600,
      newPrice: 400,
      desc: "Lorem ftdfyd dvhdudud dbjdusis uwguwuww dgudutdudd bdgsusus bvdydtuhsnbxd dxfydsydshshks vdgudguwuyw d dguysyfsyfsus ndsvhdgududiywsywbsd sgusugsdgydtsbvdvdgdsd dfysgusgusvds dgdgyd dgudhusds dgdugd bnxdhgdsjbs.",
      color: "Sandal",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686414852/MY%20ECOMMERCE/product9_850x_ukhgza.jpg",
      category: "Heels",
      isFeatured: false,
      trending: true,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Stiletto Sandals R",
      oldPrice: 740,
      newPrice: 540,
      desc: "Mipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui.",
      color: "Sandal",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686415037/MY%20ECOMMERCE/product22_850x_quovyx.jpg",
      category: "Heels",
      isFeatured: false,
      trending: true,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "High Heel Shoes",
      oldPrice: 740,
      newPrice: 740,
      desc: "Wuutetu dgdgud dgududiyhd dueuwekjlc  dfyrfsyiopd xspkpwftrs ncdfyhisdkissfh cndcfytsyso ndfydsfysojs sdvsyfsoujs  vsdtfdsftdodv dvsusjo",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686415202/MY%20ECOMMERCE/product7_850x_pg37lq.jpg",
      category: "Heels",
      isFeatured: false,
      trending: true,
      brand: "Chaco",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Slip On Shoes",
      oldPrice: 529,
      newPrice: 529,
      desc: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptate.",
      color: "Sandal",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686415303/MY%20ECOMMERCE/product13_850x_gj1lqb.jpg",
      category: "Heels",
      isFeatured: false,
      trending: true,
      brand: "Aldo",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Black Stiletto Heels",
      oldPrice: 1000,
      newPrice: 780,
      desc: "Afe aye oje ke le mo pe bata yh sff lo dhagi jigi logo fgsf gsgusfhyfh",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686416318/MY%20ECOMMERCE/product6_850x_wa4rz9.jpg",
      category: "Heels",
      isFeatured: false,
      trending: false,
      brand: "Mochi",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Black Formal Heels",
      oldPrice: 500,
      newPrice: 500,
      desc: "Fhjdhiydidy chduoei nd spiwuiwgd shiwiwdbcdbduus sdjgsfywshsd xcghdg sdghdsgjsd cgudhjdvbs ss sdghsgsyiwosoj dgsduswujsb gsjhsvdx ndsgjsjsdb d dsujgsjsvsd svhsjs bvsbm sjs sjgsbs bsjjdsjs dvhwsgjsj",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686415912/MY%20ECOMMERCE/product11_850x_o0j4q9.jpg",
      category: "Heels",
      isFeatured: false,
      trending: false,
      brand: "Athlego",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Polka High Heels",
      oldPrice: 560,
      newPrice: 560,
      desc: "Erspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem.",
      color: "Black",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686416174/MY%20ECOMMERCE/product10_850x_s2x8hh.jpg",
      category: "Heels",
      isFeatured: false,
      trending: false,
      brand: "Metro",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Leather Mens Slipper",
      oldPrice: 340,
      newPrice: 240,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Black",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406354/MY%20ECOMMERCE/1_nmttwp.webp",
      isFeatured: true,
      trending: false,
      brand: "Aldo",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Quickiin Mens shoes",
      oldPrice: 140,
      newPrice: 140,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Blue",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406382/MY%20ECOMMERCE/2_kp2e6w.webp",
      isFeatured: true,
      trending: false,
      brand: "Gionee",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Rexpo Womens shoes",
      oldPrice: 320,
      newPrice: 260,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Blue",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406401/MY%20ECOMMERCE/3_qc6itv.webp",
      isFeatured: true,
      trending: false,
      brand: "Aleryis",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Hollister V-Neck Knit",
      oldPrice: 880,
      newPrice: 880,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Black",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406419/MY%20ECOMMERCE/4_h1dv7o.webp",
      isFeatured: true,
      trending: false,
      brand: "Fila",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Primitive Mens shoes",
      oldPrice: 500,
      newPrice: 500,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Black",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406442/MY%20ECOMMERCE/5_lu9s2o.webp",
      isFeatured: true,
      trending: false,
      brand: "Antartic",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "New Womens High Hills",
      oldPrice: 333,
      newPrice: 330,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Grey",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406465/MY%20ECOMMERCE/6_gbbhxb.webp",
      isFeatured: true,
      trending: false,
      brand: "Fila",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Simple Fabric Shoe",
      oldPrice: 133,
      newPrice: 133,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Black",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406483/MY%20ECOMMERCE/7_apgdyz.webp",
      isFeatured: true,
      trending: false,
      brand: "Metro",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Exclusive mens shoe",
      oldPrice: 720,
      newPrice: 420,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Brown",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686406511/MY%20ECOMMERCE/8_ylq2b7.webp",
      isFeatured: true,
      trending: false,
      brand: "Allergy",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Fusce Aliquam",
      oldPrice: 920,
      newPrice: 800,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Black",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686420788/MY%20ECOMMERCE/7_rvml0t.png",
      isFeatured: false,
      trending: true,
      brand: "Antartic",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Mens Silver Wear",
      oldPrice: 1200,
      newPrice: 1000,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Silver",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686421915/MY%20ECOMMERCE/product06-600x600_dw0jsp.jpg",
      isFeatured: false,
      trending: true,
      brand: "Metro",
      creator: "johnfoyin@gmail.com",
    },
    {
      title: "Blue Run Wear",
      oldPrice: 620,
      newPrice: 620,
      desc: "Lorem ipsum dolor sit amet, consecte adipisicing elit, sed do eiusmll tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mill veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exet commodo consequat. Duis aute irure dolor",
      color: "Blue",
      category: "Sneakers",
      image:
        "https://res.cloudinary.com/dbxvk3apv/image/upload/v1686422085/MY%20ECOMMERCE/product19-600x600_sqhjd6.jpg",
      isFeatured: false,
      trending: true,
      brand: "Aldo",
      creator: "johnfoyin@gmail.com",
    },
  ],
};

export default data;
